Models/Formation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplicationEcoleWeb.Models
{
    public class Formation
    {
        [Key]
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Durée { get; set; }
        public List<Stagiaire> listStagiaires { get; set; }
        public List<Module> listModules { get; set; }
        public string DateDebut { get; set; }
        public string DateFin { get; set; }
        public int NombreInscrit { get; set; }
    }
}

Controllers/FormationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationEcoleWeb.Data;
using WebApplicationEcoleWeb.Models;

namespace WebApplicationEcoleWeb.Controllers
{
    public class FormationsController : Controller
    {
        private WebApplicationEcoleWebContext db = new WebApplicationEcoleWebContext();

        // GET: Formations
        public async Task<ActionResult> Index()
        {
            return View(await db.Formations.ToListAsync());
        }

        // GET: Formations/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formation formation = await db.Formations.FindAsync(id);
            if (formation == null)
            {
                return HttpNotFound();
            }
            return View(formation);
        }

        // GET: Formations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Formations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Titre,Durée,DateDebut,DateFin,NombreInscrit")] Formation formation)
        {
            if (ModelState.IsValid)
            {
                db.Formations.Add(formation);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(formation);
        }

        // GET: Formations/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formation formation = await db.Formations.FindAsync(id);
            if (formation == null)
            {
                return HttpNotFound();
            }
            return View(formation);
        }

        // POST: Formations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Titre,Durée,DateDebut,DateFin,NombreInscrit")] Formation formation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(formation).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(formation);
        }

        // GET: Formations/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formation formation = await db.Formations.FindAsync(id);
            if (formation == null)
            {
                return HttpNotFound();
            }
            return View(formation);
        }

        // POST: Formations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Formation formation = await db.Formations.FindAsync(id);
            db.Formations.Remove(formation);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        
        //Get: Formations/Inscription
        public ActionResult Inscription()
        {
            ViewBag.inscrit = db.Formations.FirstOrDefault().NombreInscrit;

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Formations/Create.cshtml
@model WebApplicationEcoleWeb.Models.Formation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Formation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Durée, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Durée, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Durée, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateDebut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDebut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateDebut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateFin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreInscrit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreInscrit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreInscrit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Formations/Delete.cshtml
@model WebApplicationEcoleWeb.Models.Formation

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Formation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durée)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durée)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateDebut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateDebut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreInscrit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreInscrit)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Formations/Details.cshtml
@model WebApplicationEcoleWeb.Models.Formation

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Formation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durée)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durée)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateDebut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateDebut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreInscrit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreInscrit)
        </dd>

    </dl>
</div>
<p>
   
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Formations/Edit.cshtml
@model WebApplicationEcoleWeb.Models.Formation

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Formation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Durée, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Durée, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Durée, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateDebut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDebut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateDebut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateFin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreInscrit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreInscrit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreInscrit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Formations/Index.cshtml
@model IEnumerable<WebApplicationEcoleWeb.Models.Formation>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Durée)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateDebut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateFin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NombreInscrit)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Durée)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateDebut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateFin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreInscrit)
            </td>
            <td>
                @if (Session["roleUtilisateur"] != null)
                {
                    if (Session["roleUtilisateur"].Equals("Administrateur"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })

                    }
                }

                @if (Session["roleUtilisateur"] != null)
                {
                    if (Session["roleUtilisateur"].Equals("Administrateur"))
                    {
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id });
                    }
                }

                @Html.ActionLink("Details", "Details", new { id = item.Id })

                @if (Session["roleUtilisateur"] == null)
                {
                    @Html.ActionLink("Inscription Register", "Register", "Account")
                }

                @if (Session["roleUtilisateur"] != null)
                {
                    if (Session["roleUtilisateur"].Equals("Stagiaire"))
                    {
                        @Html.ActionLink("Inscription à la Formation", "Inscription", "Formations", new { id = item.Id })
                    }
                }
                



                </td>
                </tr>
                    }


</table>
<style>

    body {
        background-color: antiquewhite;
    }


    .vertical .carousel-inner {
        height: 100%;
    }



    .carousel.vertical .active {
        top: 0;
    }

    .carousel.vertical .next {
        top: 100%;
    }

    .carousel.vertical .prev {
        top: -100%;
    }

        .carousel.vertical .next.left,
        .carousel.vertical .prev.right {
            top: 0;
        }

    .carousel.vertical .active.left {
        top: -100%;
    }

    .carousel.vertical .active.right {
        top: 100%;
    }
</style>

Views/Formations/Inscription.cshtml
@{
    ViewBag.Title = "Inscription";
}

<h1>
    Vous êtes le @ViewBag.inscrit inscrit!!
</h1>